

# send a welcome message for specific users
message "Welcome, Victor." if github.pr_author == "Vkt0r"

# Just to let people know
warn("PR is classed as Work in Progress.") if github.pr_title.include? "[WIP]"

# ensure that the PR have an assignee
warn "This PR does not have any assignees yet." unless github.pr_json["assignee"]

# Warn when there is a big PR
warn("Big PR") if git.lines_of_code > 500

# ensure there is a summary for a PR
fail "Please provide a summary in the Pull Request description." if github.pr_body.length < 5

# Changelog entries are required for changes to library files.
fail("No CHANGELOG changes made. Please update your the CHANGELOG file with the latest changes @#{github.pr_author}") unless git.modified_files.include?("CHANGELOG.yml")

# If these are all empty something has gone wrong, better to raise it in a comment
if git.modified_files.empty? && git.added_files.empty? && git.deleted_files.empty?
  fail "This PR has no changes at all, this is likely a developer issue."
end

# note whe a pr cannot be manually merged, which goes away when you can
can_merge = github.pr_json["mergeable"]
warn("This PR cannot be merged yet.", sticky: false) unless can_merge

# Run SwiftLint
swiftlint.config_file = '.swiftlint.yml'
swiftlint.lint_files
