fastlane_version "1.108.0"

default_platform :ios

platform :ios do
  desc "Runs all the tests"
  lane :test do
    scan(
        scheme: "AccordionMenuSwift",
        clean: true,
        sdk: "iphonesimulator",
        destination: "name=iPhone 6"
    )
  end
end
